name: Build & Test on Main Branch Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn

    - name: Build Project
      run: yarn build

    - name: Execute Tests
      env:
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
        DB_COLLECTION_DEV: ${{ secrets.DB_COLLECTION_DEV }}
        DB_COLLECTION_PROD: ${{ secrets.DB_COLLECTION_PROD }}
        DB_URL: ${{ secrets.DB_URL }}
        ENV: ${{ secrets.ENV }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        LOG: ${{ secrets.LOG }}
        MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
        MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        PORT: ${{ secrets.PORT }}
      run: yarn test-core