name: Build & Test on Main Branch Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn

    - name: Build Project
      run: yarn build

    - name: Configure .env for local runner
      if: github.actions == 'true'
      run: |
        export LOG=1
        export ENV=DEV
        export PORT=3000
        export BACKEND_URL=${{ secrets.BACKEND_URL }}
        export DB_COLLECTION_DEV=${{ secrets.DB_COLLECTION_DEV }}
        export DB_COLLECTION_PROD=${{ secrets.DB_COLLECTION_PROD }}
        export DB_URL=${{ secrets.DB_URL }}
        export JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
        export JWT_SECRET=${{ secrets.JWT_SECRET }}
        export MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}
        export MAILJET_SECRET_KEY=${{ secrets.MAILJET_SECRET_KEY }}
        export OPENAI_KEY=${{ secrets.OPENAI_KEY }}

    - name: Run tests
      run: yarn test-core